services:
  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - ./.env
  
  mongodb:
    image:  mongo
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
